### ISSUE TITLE
اصلاح فرمت تاریخ ها

### ISSUE THREAD

**Issue by mehrdadmmb2** [hamsaadev/Persian-Date-Picker-Dialog#10]
سلام دوست عزیز
تاریخ ها برای اعداد تک رقمی باید با صفر همراه باشه مثل:
1396/09/06
نه 
1396/9/6
اگر ممکنه اصلاح بفرمایید، دوستان به مشکل بر میخورن
با تشکر از زحمات شما

**Comment by aliab** [comment]
چون این موضوع دلبخواهی هست٬‌ لطفا عدد را بر اساس نیاز خودتون فرمت کنید

**Comment by iman2420** [comment]
@mehrdadmmb2 Like=>

`String.format("%02d", persianPickerDate.persianMonth)`
