### ISSUE TITLE
تبدیل تاریخ دریافتی به رشته

### ISSUE THREAD

**Issue by Amin1972** [hamsaadev/Persian-Date-Picker-Dialog#2]
سلام دوست عزیز ممنون بابت این کتابخانه کاربردی . در تلاشم تاریخ دریافتی را به string تبدیل کنم.
آیا این قابلیت فعال هست ؟ چطور باید تاریخ گرفته شده را به فرمت yyyy-mm-dd تبدیل کنیم؟
باتشکر

**Comment by aliab** [comment]
سلام٬ بعد از انتخاب تاریخ یک Instance از کلاس PersianCalendar بهتون داده شده که فکر میکنم یه نگاهی بهش بندازین تمام مواردی که دنبالش هستین رو پیدا میکنین
