### ISSUE TITLE
نحوه استفاده در پروژه جدید

### ISSUE THREAD

**Issue by msd1357** [hamsaadev/Persian-Date-Picker-Dialog#5]
سلام دوست عزیز
شاید سوال من خیلی ارتباط به موضوع نداشته باشه.جون من تقریباً تازه کار هستم.
.لطفاً اگه ممکنه دقیق تر توضیح بدید چطور از لایبرری شما در یه پروژه استفاده کنم
طبق توضیحات شما و چندین روش مختلف انجام دادم اما نتونستم
بعد از اضافه کردن لایبری شما به پروژه اندروید استودیو خودم دارای 3 تا فایل 
Build.gradle
میشه. کدهای شمارو به کدوم اضافه کنم؟

**Comment by davidjonz2005** [comment]
خود این پروژه یک دمو هست که توشاز لایبری استفاده شده
