### ISSUE TITLE
حداقل تاریخ

### ISSUE THREAD

**Issue by MahdiPishguy** [hamsaadev/Persian-Date-Picker-Dialog#6]
تعجب میکنم چرا تو توضیحات ننوشتید که تاریخ ها مابین چیا باید باشه. یعنی کسی که سال مثلا ۷۰ به دنیااومده باشه امکان پذیر نیست؟ حداقل توضیح بدید.

این خیلی تغییرات میخاد قابل استفاده باشه. کاربردی نداره به صورت استفاده عادی

**Comment by aliab** [comment]
ممنون که این موضوع رو ذکر کردید٬ تاریخ های حداقل و حداکثر رو اگر تنظیم نکنید به طور خودکار ۱۰ سال کمتر و بیشتر از امسال به عنوان سال های پایین و بالا تنظیم خواهد شد
خوشحال مشیم مواردی که لازمه اضافه بشه یا 
PR
بفرستید یا بگید که اصلاح کنیم
